import time
'''
print time.sleep(0)
sleeps the program for a number of seconds
print time.tzname
prints the timezone's name (EST)
print time.clock()
prints the clock speed of the computer's microprocessor in seconds
print time.time()
prints the number of seconds since the epoch (last day before 1970)(uses the system clock)
'''

print " _____________________________________________________________________________________ "
print "|               __  __  _     ___   _                  __      _         _            |"
print "|           |/ |_  |_  |_)     |   /_\  |   |/ | |\ | / _\    /_\  |\ | | \           |"
print "|           |\ |__ |__ |       |  /   \ |__ |\ | | \| \__|   /   \ | \| |_/           |"
print "|                  _   _   _   _          __     _       _   _   __   _               |"
print "|            |\ | / \ |_) / \ | \ \ /    |_  \/ |_) |   / \ | \ |_   ( >              |"
print "|            | \| \_/ |_) \_/ |_/  |     |__ /\ |   |__ \_/ |_/ |__ <_)               |"
print "|                                                                                     |"
print "|                    ______       _____      __      __    ______                     |"
print "|                   |   _  \     /  _  \    |  \    /  |  |   _  \                    |"
print "|                   |  |_)  )   /  / \  \   |   \  /   |  |  |_)  )                   |"
print "|                   |      /   |  |   |  |  |  \ \/ /  |  |      /                    |"
print "|                   |   _  \   |  |   |  |  |  |\  /|  |  |   _  \                    |"
print "|                   |  |_)  )   \  \_/  /   |  | \/ |  |  |  |_)  )                   |"
print "|                   |______/     \_____/    |__|    |__|  |______/                    |"
print "|                                                                                     |"
print "|          ___       _____    _____    __  __    ____        _        __              |"
print "|         |   '-.   |   __)  |   __)  |  ||  |  /    \      / \      |  |             |"
print "|         |  |\  \  |  |_    |  |_    |  ||  |  \  \_/     / _ \     |  |             |"
print "|         |  | )  ) |   _)   |   _)   |  ||  |   \  \     / /_\ \    |  |             |"
print "|         |  |/  /  |  |__   |  |     |  \/  |  / \  \   /  ___  \   |  |___          |"
print "|         |___.-'   |_____)  |__|      \____/   \____/  /__/   \__\  |______)         |"
print "|                                                                                     |"
print "|            _      _        _        _   _    _  _        _        _                 |"
print "|           | \    / |      / \      | \ | |  | || |      / \      | |                |"
print "|           |  \  /  |     / _ \     |  \| |  | || |     / _ \     | |                |"
print "|           | \ \/ / |    / /_\ \    | \ \ |  | || |    / /_\ \    | |                |"
print "|           | |\  /| |   / _____ \   | |\  |  | \/ |   / _____ \   | |____            |"
print "|           |_| \/ |_|  /_/     \_\  |_| \_|   \__/   /_/     \_\  |______)           |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                      Version 1                                      |"
print "|                           Verification Code:", round(time.time(), 1), "                          |"
print "|               For",time.tzname,"               |"
print "|  Identification:",time.clock(),"                                                             |"
print "|_____________________________________________________________________________________|"
time.sleep (1)
print " _____________________________________________________________________________________ "
print "|                                                                                     |"
print "| Keep Talking and Nobody Explodes v.1                                                |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|          Welcome to the dangerous and challenging world of bomb defusing.           |"
print "|                                                                                     |"
print "|    Study this manual carefully; you are the expert. In these pages you will find    |"
print "|       everything you need to know to defuse even the most insidious of bombs.       |"
print "|            And remember - One small oversight and it could all be over!             |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|                                     Page 2 of 3                                     |"
print "|_____________________________________________________________________________________|"
time.sleep (1)
print " _____________________________________________________________________________________ "
print "|                                                                                     |"
print "| Keep Talking and Nobody Explodes v.1                                                |"
print "|                                                                                     |"
print "|                                                                                     |"
print "|    On the Subject of Wires:                                                         |"
print "|                                                                                     |"
print "|    Wires are the lifeblood of electronics! Wait, no, electricity is the lifeblood.  |"
print "|    Wires are more like the arteries. The veins? No matter...                        |"
print "|                                                                                     |"
print "|        - A wire module can have 3-6 wires on it.                                    |"
print "|        - Only the one correct wire needs to be cut to disarm the module.            |"
print "|        - Wire ordering begins with the first on the top.                            |"
print "|        - To cut a wire, type: [COLOUR-#]                                            |"
print "|     ___________________________________________________________________________     |"
print "|    | 3 Wires:                                                                  |    |"
print "|    | If there are no red wires, cut the second wire.                           |    |"
print "|    |                                                                           |    |"
print "|    | Otherwise, if the last wire is white, cut the last wire.                  |    |"
print "|    |                                                                           |    |"
print "|    | Otherwise, if there is more than one blue wire, cut the last blue wire.   |    |"
print "|    |                                                                           |    |"
print "|    | Otherwise, cut the last wire.                                             |    |"
print "|    |___________________________________________________________________________|    |"
print "|    | 4 Wires:                                                                  |    |"
print "|    | If there is more than one red wire, cut the last red wire.                |    |"
print "|    |                                                                           |    |"
print "|    | Otherwise, if the last wire is yellow and there are no red wires, cut the |    |"
print "|    | first wire.                                                               |    |"
print "|    |                                                                           |    |"
print "|    | Otherwise, if there is exactly one blue wire, cut the first wire.         |    |"
print "|    |                                                                           |    |"
print "|    | Otherwise, if there is more than one yellow wire, cut the last wire.      |    |"
print "|    |                                                                           |    |"
print "|    | Otherwise, cut the second wire.                                           |    |"
print "|    |___________________________________________________________________________|    |"
print "|    | 5 Wires:                                                                  |    |"
print "|    | If the last wire is black, cut the fourth wire.                           |    |"
print "|    |                                                                           |    |"
print "|    | Otherwise, if there is exactly one red wire and there is more than one    |    |"
print "|    | yellow wire, cut the first wire.                                          |    |"
print "|    |                                                                           |    |"
print "|    | Otherwise, if there are no black wires, cut the second wire.              |    |"
print "|    |                                                                           |    |"
print "|    | Otherwise, cut the first wire.                                            |    |"
print "|    |___________________________________________________________________________|    |"
print "|    | 6 Wires:                                                                  |    |"
print "|    | If there are no yellow wires, cut the third wire.                         |    |"
print "|    |                                                                           |    |"
print "|    | Otherwise, if there is exactly one yellow wire and there is more than one |    |"
print "|    | white wire, cut the fourth wire.                                          |    |"
print "|    |                                                                           |    |"
print "|    | Otherwise, if there are no red wires, cut the last wire.                  |    |"
print "|    |                                                                           |    |"
print "|    | Otherwise, cut the fourth wire.                                           |    |"
print "|    |___________________________________________________________________________|    |"
print "|                                                                                     |"
print "|                                     Page 3 of 3                                     |"
print "|_____________________________________________________________________________________|"